### ISSUE TITLE
raise KeyError(f"ID not found: {peer_id}")

### ISSUE THREAD

**Issue by bit1001** [tropicoo/yt-dlp-bot#100]
port_pool' with 4 processes in it
yt_rabbitmq  | 2023-04-22 13:18:50.644955+00:00 [info] <0.230.0> Running boot step cluster_name defined by app rabbit
yt_rabbitmq  | 2023-04-22 13:18:50.645007+00:00 [info] <0.230.0> Running boot step direct_client defined by app rabbit
yt_rabbitmq  | 2023-04-22 13:18:50.645120+00:00 [info] <0.230.0> Running boot step rabbit_maintenance_mode_state defined by app rabbit
yt_rabbitmq  | 2023-04-22 13:18:50.645150+00:00 [info] <0.230.0> Creating table rabbit_node_maintenance_states for maintenance mode status
yt_rabbitmq  | 2023-04-22 13:18:50.645452+00:00 [info] <0.230.0> Running boot step rabbit_management_load_definitions defined by app rabbitmq_management
yt_rabbitmq  | 2023-04-22 13:18:50.645582+00:00 [info] <0.526.0> Resetting node maintenance status
yt_rabbitmq  | 2023-04-22 13:18:50.659434+00:00 [info] <0.585.0> Management plugin: HTTP (non-TLS) listener started on port 15672
yt_rabbitmq  | 2023-04-22 13:18:50.659616+00:00 [info] <0.613.0> Statistics database started.
yt_rabbitmq  | 2023-04-22 13:18:50.659681+00:00 [info] <0.612.0> Starting worker pool 'management_worker_pool' with 3 processes in it
yt_rabbitmq  | 2023-04-22 13:18:50.671770+00:00 [info] <0.627.0> Prometheus metrics: HTTP (non-TLS) listener started on port 15692
yt_rabbitmq  | 2023-04-22 13:18:50.672032+00:00 [info] <0.526.0> Ready to start client connection listeners
yt_rabbitmq  | 2023-04-22 13:18:50.673980+00:00 [info] <0.671.0> started TCP listener on [::]:5672
yt_rabbitmq  |  completed with 4 plugins.
yt_rabbitmq  | 2023-04-22 13:18:50.839267+00:00 [info] <0.526.0> Server startup complete; 4 plugins started.
yt_rabbitmq  | 2023-04-22 13:18:50.839267+00:00 [info] <0.526.0>  * rabbitmq_prometheus
yt_rabbitmq  | 2023-04-22 13:18:50.839267+00:00 [info] <0.526.0>  * rabbitmq_management
yt_rabbitmq  | 2023-04-22 13:18:50.839267+00:00 [info] <0.526.0>  * rabbitmq_web_dispatch
yt_rabbitmq  | 2023-04-22 13:18:50.839267+00:00 [info] <0.526.0>  * rabbitmq_management_agent
yt_bot       | Waiting for RabbitMQ to be reachable on port 5672
yt_bot       | Connection to RabbitMQ on port 5672 verified
yt_worker    | Waiting for RabbitMQ to be reachable on port 5672
yt_worker    | Connection to RabbitMQ on port 5672 verified
yt_api       | Waiting for RabbitMQ to be reachable on port 5672
yt_api       | Connection to RabbitMQ on port 5672 verified
yt_worker    | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
yt_worker    | INFO  [alembic.runtime.migration] Will assume transactional DDL.
yt_bot       | 2023-04-22 13:18:52,332 - [INFO] - [VideoBot:27] - Initializing bot client
yt_rabbitmq  | 2023-04-22 13:18:52.340062+00:00 [info] <0.689.0> accepting AMQP connection <0.689.0> (172.19.0.7:44350 -> 172.19.0.4:5672)
yt_rabbitmq  | 2023-04-22 13:18:52.344179+00:00 [info] <0.689.0> connection <0.689.0> (172.19.0.7:44350 -> 172.19.0.4:5672): user 'guest' authenticated and granted access to vhost '/'
yt_bot       | 2023-04-22 13:18:52,586 - [WARNING] - [asyncio:118] - Executing <Task pending name='Task-1' coro=<main() running at /app/main.py:13> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/tasks.py:456> cb=[run_until_complete.<locals>.done_cb()] created at /usr/local/lib/python3.11/asyncio/runners.py:100> took 0.221 seconds
yt_worker    | 2023-04-22 13:18:52,690 - [INFO] - [WorkerLauncher:24] - Starting download worker instance
yt_worker    | 2023-04-22 13:18:52,691 - [INFO] - [WorkerLauncher:45] - Setting up RabbitMQ connection
yt_worker    | 2023-04-22 13:18:52,692 - [INFO] - [WorkerLauncher:54] - Saving current yt-dlp version (2023.03.04) to the database
yt_worker    | 2023-04-22 13:18:52,698 - [INFO] - [WorkerLauncher:68] - Creating intermediate directories ('/tmp/download_tmpfs/downloading', '/tmp/download_tmpfs/downloaded') if not exist
yt_rabbitmq  | 2023-04-22 13:18:52.705434+00:00 [info] <0.705.0> accepting AMQP connection <0.705.0> (172.19.0.5:33042 -> 172.19.0.4:5672)
yt_rabbitmq  | 2023-04-22 13:18:52.753455+00:00 [info] <0.705.0> connection <0.705.0> (172.19.0.5:33042 -> 172.19.0.4:5672): user 'guest' authenticated and granted access to vhost '/'
yt_api       | INFO:     Started server process [1]
yt_api       | INFO:     Waiting for application startup.
yt_api       | 2023-04-22 13:18:52,824 - [WARNING] - [asyncio:118] - Executing <Task pending name='Task-1' coro=<Server.serve() running at /usr/local/lib/python3.11/site-packages/uvicorn/server.py:76> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/locks.py:210> cb=[run_until_complete.<locals>.done_cb()] created at /usr/local/lib/python3.11/asyncio/runners.py:100> took 1.087 seconds
yt_rabbitmq  | 2023-04-22 13:18:52.831485+00:00 [info] <0.721.0> accepting AMQP connection <0.721.0> (172.19.0.6:52698 -> 172.19.0.4:5672)
yt_rabbitmq  | 2023-04-22 13:18:52.834539+00:00 [info] <0.721.0> connection <0.721.0> (172.19.0.6:52698 -> 172.19.0.4:5672): user 'guest' authenticated and granted access to vhost '/'
yt_api       | INFO:     Application startup complete.
yt_api       | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
yt_bot       | 2023-04-22 13:18:56,548 - [INFO] - [BotLauncher:82] - Starting "zytdlbot" bot
yt_bot       | 2023-04-22 13:18:56,548 - [INFO] - [VideoBot:49] - Sending welcome message
yt_rabbitmq  | 2023-04-22 13:18:56.804694+00:00 [info] <0.689.0> closing AMQP connection <0.689.0> (172.19.0.7:44350 -> 172.19.0.4:5672, vhost: '/', user: 'guest')
yt_bot       | 2023-04-22 13:18:56,812 - [INFO] - [aio_pika.robust_connection:77] - Connection to amqp://guest:******@yt_rabbitmq:5672/ closed. Reconnecting after 5 seconds.
yt_bot       | Traceback (most recent call last):
yt_bot       |   File "/usr/local/lib/python3.11/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 62, in resolve_peer
yt_bot       |     return await self.storage.get_peer_by_id(peer_id)
yt_bot       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yt_bot       |   File "/usr/local/lib/python3.11/site-packages/pyrogram/storage/sqlite_storage.py", line 142, in get_peer_by_id
yt_bot       |     raise KeyError(f"ID not found: {peer_id}")
yt_bot       | KeyError: 'ID not found: 0'
yt_bot       |
yt_bot       | During handling of the above exception, another exception occurred:
yt_bot       |
yt_bot       | Traceback (most recent call last):
yt_bot       |   File "/app/main.py", line 18, in <module>
yt_bot       |     asyncio.run(main())
yt_bot       |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
yt_bot       |     return runner.run(main)
yt_bot       |            ^^^^^^^^^^^^^^^^
yt_bot       |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
yt_bot       |     return self._loop.run_until_complete(task)
yt_bot       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yt_bot       |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
yt_bot       |   File "/app/main.py", line 13, in main
yt_bot       |     await BotLauncher().run()
yt_bot       |   File "/app/bot/core/bot/launcher.py", line 32, in run
yt_bot       |     await self._start_bot()
yt_bot       |   File "/app/bot/core/bot/launcher.py", line 83, in _start_bot
yt_bot       |     await self._bot.send_startup_message()
yt_bot       |   File "/app/bot/core/bot/bot.py", line 50, in send_startup_message
yt_bot       |     await self.send_message_to_users(
yt_bot       |   File "/app/bot/core/bot/bot.py", line 64, in send_message_to_users
yt_bot       |     await asyncio.gather(*coros)
yt_bot       |   File "/usr/local/lib/python3.11/site-packages/pyrogram/methods/messages/send_message.py", line 128, in send_message
yt_bot       |     peer=await self.resolve_peer(chat_id),
yt_bot       |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yt_bot       |   File "/usr/local/lib/python3.11/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 89, in resolve_peer
yt_bot       |     peer_type = utils.get_peer_type(peer_id)
yt_bot       |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yt_bot       |   File "/usr/local/lib/python3.11/site-packages/pyrogram/utils.py", line 246, in get_peer_type
yt_bot       |     raise ValueError(f"Peer id invalid: {peer_id}")
yt_bot       | ValueError: Peer id invalid: 0
yt_bot       | 2023-04-22 13:18:56,958 - [ERROR] - [asyncio:1518] - Task was destroyed but it is pending!
yt_bot       | source_traceback: Object created at (most recent call last):
yt_bot       |   File "/app/main.py", line 18, in <module>
yt_bot       |     asyncio.run(main())
yt_bot       |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 189, in run
yt_bot       |     with Runner(debug=debug) as runner:
yt_bot       |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 63, in __exit__
yt_bot       |     self.close()
yt_bot       |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 72, in close
yt_bot       |     loop.run_until_complete(loop.shutdown_asyncgens())
yt_bot       |   File "/usr/local/lib/python3.11/site-packages/aio_pika/tools.py", line 248, in __call__
yt_bot       |     self.__task = self.loop.create_task(
yt_bot       | task: <Task pending name='Task-139' coro=<OneShotCallback.__task_inner() running at /usr/local/lib/python3.11/site-packages/aio_pika/tools.py:239> wait_for=<_GatheringFuture finished result=[None, None, None, None] created at /usr/local/lib/python3.11/asyncio/tasks.py:699> created at /usr/local/lib/python3.11/site-packages/aio_pika/tools.py:248>
yt_bot       | Exception ignored in: <coroutine object OneShotCallback.__task_inner at 0x7fc14e30c130>
yt_bot       | Traceback (most recent call last):
yt_bot       |   File "/usr/local/lib/python3.11/site-packages/aio_pika/tools.py", line 241, in __task_inner
yt_bot       |   File "uvloop/loop.pyx", line 1281, in uvloop.loop.Loop.call_soon
yt_bot       |   File "uvloop/loop.pyx", line 667, in uvloop.loop.Loop._call_soon
yt_bot       |   File "uvloop/loop.pyx", line 676, in uvloop.loop.Loop._call_soon_handle
yt_bot       |   File "uvloop/loop.pyx", line 671, in uvloop.loop.Loop._append_ready_handle
yt_bot       |   File "uvloop/loop.pyx", line 703, in uvloop.loop.Loop._check_closed
yt_bot       | RuntimeError: Event loop is closed
yt_bot exited with code 0

**Comment by tropicoo** [comment]
Could you please check your config whether you have your peer ID set to 0?
`ValueError: Peer id invalid: 0`

**Comment by bit1001** [comment]
> Could you please check your config whether you have your peer ID set to 0? `ValueError: Peer id invalid: 0`

Problem solved. Thanks.
