### ISSUE TITLE
asynco problem

### ISSUE THREAD

**Issue by mostafahn** [tropicoo/yt-dlp-bot#123]
for some videos

yt_api       | 2023-06-13 07:38:03,319 - [WARNING] - [asyncio:118] - Executing <Task pending name='Task-1' coro=<Server.serve() running at /usr/local/lib/python3.11/site-packages/uvicorn/server.py:81> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/tasks.py:634> cb=[run_until_complete.<locals>.done_cb()] created at /usr/local/lib/python3.11/asyncio/runners.py:100> took 0.126 seconds

**Comment by mostafahn** [comment]
yes, you are right
but for some video, bot cant upload video and cpu usage 100% it will be ready after minuts.
i tried to change this file:  /yt-dlp-bot/app_worker/ytdl_opts/default.py

change from:
VIDEO_YTDL_OPTS = [
    '--format',
    'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4',
    '--write-thumbnail',
    '--convert-thumbnails',
    FINAL_THUMBNAIL_FORMAT,
]
to:
VIDEO_YTDL_OPTS = [
    '--format',
    '(bv*[height<=480])[ext=mp4]+ba[ext=m4a]/(b[height<=480])[ext=mp4] / wv*[ext=mp4]+(ba/w)[ext=m4a]',
    '--write-thumbnail',
    '--convert-thumbnails',
    FINAL_THUMBNAIL_FORMAT,
]

everything looks good now

**Comment by tropicoo** [comment]
> bot cant upload video and cpu usage 100% it will be ready after minutes.

Telegram has a limit of 2GB for regular users and 4GB for premium.
CPU is 100% probably because it's mixing the large video and audio files into one file before uploading. That's expected behavior.

**Comment by mostafahn** [comment]
thank you
