### ISSUE TITLE
Forward To Group and Chat Id's not working

### ISSUE THREAD

**Issue by ShamilSd-ux** [tropicoo/yt-dlp-bot#141]
I have deployed bot on my Windows machine ;bot is working; video is uploaded to only chat in bot "Forward to Group", "Forward to chat Id's " are not working;
And allowed users only one id is allowed 
At end of every video this error persists every time...

🛑 General error

ℹ Task ID: a4f4a540-c3eb-4ac7-80de-eb8ae0077456
💬 Message: Upload error
📹 Video URL: https://www.youtube.com/watch?v=ZYaZ6Odbx_Y&pp=ygUPYWwgZmF0aWhhIHN1cmFo
🌊 Source: BOT
👀 Details: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 62, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyrogram/storage/sqlite_storage.py", line 142, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: -1001812523689'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bot/core/handlers/success.py", line 61, in _handle
    await self._create_upload_task(media_object)
  File "/app/bot/core/handlers/success.py", line 86, in _create_upload_task
    await create_task(
pyrogram.errors.exceptions.bad_request_400.ChannelInvalid: Telegram says: [400 CHANNEL_INVALID] - The channel parameter is invalid (caused by "channels.GetChannels")

⬇️ yt-dlp version: 2023.07.06
🤖 yt-dlp-bot version: 1.4.1
🏷️ Tag: #error

**Comment by tropicoo** [comment]
Are you sure that this group id is valid and the bot was added there?

**Comment by ShamilSd-ux** [comment]
Yes. 
![image](https://github.com/tropicoo/yt-dlp-bot/assets/81691084/1bbce8cc-f92b-43c5-a1cf-e1fb171cabc3)

**Comment by tropicoo** [comment]
Please share your config

**Comment by tropicoo** [comment]
Your channel has 1 subscriber (you). You must the bot to the channel.

**Comment by ShamilSd-ux** [comment]
What is your  telegram username?

**Comment by tropicoo** [comment]
I don't think that two bots will work since they both would receive the same messages

**Comment by ShamilSd-ux** [comment]
I want to deploy it for other  telegram account. As docker works as containers. Can't we create another container?

**Comment by tropicoo** [comment]
You can try to copy the bot directory to another one and edit the `docker-compose.yml` by changing the `api, bot, worker` services container names to different ones and build/run as usual.

**Comment by ShamilSd-ux** [comment]
This isn't working. There are some conflicts with postgres ports and I may be not qualified to do config. Anyhow I am grateful for your contribution so far. I hope you make my request. I am applying for bitcoin wallet and hope to donate you asap. And i will be delighted if you provide a telegram id for a private chat.

**Comment by tropicoo** [comment]
Do you still have issues?

**Comment by ShamilSd-ux** [comment]
I am expecting to have video quality settings option as videos are rendered in high quality and we can't save 4k videos with 2 GB limit.
I have created an enhancement by which you can automate a playlist and save videos to telegram group.😊
And I feel bot should be developed by which we can configure it from the UI without having to modify config from terminal or IDE...

**Comment by ShamilSd-ux** [comment]
Bot is not triggered when video urls are sent to the bot directly...

**Comment by tropicoo** [comment]
You can ping me in the telegram @rare_vision

**Comment by tropicoo** [comment]
> I am expecting to have video quality settings option as videos are rendered in high quality and we can't save 4k videos with 2 GB limit.

You can change the settings https://github.com/tropicoo/yt-dlp-bot/blob/a3536073e67999e23a927ec66a4588725eaee60c/app_worker/ytdl_opts/default.py#L42

to something like this: `'bestvideo[ext=mp4][filesize<=2000MB]+bestaudio[ext=m4a]/mp4',`

**Comment by tropicoo** [comment]
> And I feel bot should be developed by which we can configure it from the UI without having to modify config from terminal or IDE...

That's really _a lot of work and rework_ :)

**Comment by ShamilSd-ux** [comment]
> 



> > I am expecting to have video quality settings option as videos are rendered in high quality and we can't save 4k videos with 2 GB limit.
> 
> You can change the settings
> 
> https://github.com/tropicoo/yt-dlp-bot/blob/a3536073e67999e23a927ec66a4588725eaee60c/app_worker/ytdl_opts/default.py#L42
> 
> to something like this: `'bestvideo[ext=mp4][filesize<=2000MB]+bestaudio[ext=m4a]/mp4',`

This isn't Working...

**Comment by ShamilSd-ux** [comment]
> > And I feel bot should be developed by which we can configure it from the UI without having to modify config from terminal or IDE...
> 
> That's really _a lot of work and rework_ :)

Thanks for consideration. Let the features be implemented in course of time...

**Comment by tropicoo** [comment]
> This isn't Working...

That's strange, I've tested that locally and it definitely did choose the right video.
Can you post logs?

**Comment by ShamilSd-ux** [comment]
> > This isn't Working...
> 
> That's strange, I've tested that locally and it definitely did choose the right video. Can you post logs?

I have given a 4k video and it chose a file range of 2.3 GB. Logs are in VPS somewhere...  Do you have any ideas to improve bot!?.

**Comment by ShamilSd-ux** [comment]
> > This isn't Working...
> 
> That's strange, I've tested that locally and it definitely did choose the right video. Can you post logs?

It's working but there is a small catch. If the next best quality is slightly more than 2 GB then the upload is failing. And recently build is failed because of PyYAML got new version in its repository. Is there any automatic way to update versions in requirements file to have successful build without intervention....

**Comment by PalashMudi** [comment]
any solution found? @tropicoo @ShamilSd-ux

**Comment by tropicoo** [comment]
@PalashMudi Please open new issue since the original one is resolved
