### ISSUE TITLE
The bot did not receive a response

### ISSUE THREAD

**Issue by LRboyz** [tropicoo/yt-dlp-bot#166]
I followed the tutorial and everything ran smoothly, but my telegram did not receive a response from the robot. This is a screenshot of the console. Can you help me find out what went wrong?
![image](https://github.com/tropicoo/yt-dlp-bot/assets/48092353/3840049d-2252-45e5-abf8-05654627ad16)

**Comment by tropicoo** [comment]
That's the first time I'm seeing something like this. Looks like a bug in the Pyrogram library. Is it a permanent error or was that a temporary issue?

**Comment by LRboyz** [comment]
🙏Thank you for your reply, this is just a problem, and I pulled your latest code, and followed the tutorials in the document all the way, and then I entered docker to check and found that it was the console error in yt_bot , the error is as follows：
![image](https://github.com/tropicoo/yt-dlp-bot/assets/48092353/37c4a875-744b-432f-bf73-fd9ff9918774)
Can you see what the problem is?

**Comment by tropicoo** [comment]
Unfortunately, there's nothing personally I can do about this. You can read the Pyrogram's author response here https://github.com/pyrogram/pyrogram/issues/1249#issuecomment-1501055946
