### ISSUE TITLE
Links not getting rendered.

### ISSUE THREAD

**Issue by ShamilSd-ux** [tropicoo/yt-dlp-bot#172]
Links given in groups that has  bot as admin are not getting rendered. How can we add bot to different groups if this is not working?

**Comment by tropicoo** [comment]
I've just tested, it works. Check your configuration

**Comment by ShamilSd-ux** [comment]
![image](https://github.com/tropicoo/yt-dlp-bot/assets/81691084/705cc1b9-b025-4a59-8031-10209f29976f)
Look No response in group.

**Comment by irreverends** [comment]
> ![image](https://user-images.githubusercontent.com/81691084/265204244-c145ca8c-6599-40c0-b260-e5791e7d9a02.png)
> 
> Look, No response in Group...

I was having this issue. My problem was firstly that I hadn't changed the Telegram bot privacy setting to allow it to access messages, but then after I had done, I had to remove and add the bot again. It still couldn't see messages until I'd re-added it.

**Comment by ShamilSd-ux** [comment]
> > ![image](https://user-images.githubusercontent.com/81691084/265204244-c145ca8c-6599-40c0-b260-e5791e7d9a02.png)
> > Look, No response in Group...
> 
> I was having this issue. My problem was firstly that I hadn't changed the Telegram bot privacy setting to allow it to access messages, but then after I had done, I had to remove and add the bot again. It still couldn't see messages until I'd re-added it.

Are you pasting youtube links in Bot or Group?

**Comment by irreverends** [comment]
> > > ![image](https://user-images.githubusercontent.com/81691084/265204244-c145ca8c-6599-40c0-b260-e5791e7d9a02.png)
> > > Look, No response in Group...
> > 
> > 
> > I was having this issue. My problem was firstly that I hadn't changed the Telegram bot privacy setting to allow it to access messages, but then after I had done, I had to remove and add the bot again. It still couldn't see messages until I'd re-added it.
> 
> Are you pasting youtube links in Bot or Group?

Group. like I said, my issue was resolved by removing the bot and adding it again. It still wasn't able to see group messages because I changed the botfather privacy setting after I'd added it to the group.

**Comment by ShamilSd-ux** [comment]
I want to send youtube link in a group and bot should render it and post video in the group

**Comment by irreverends** [comment]
> I want to send youtube link in a group and bot should render it and post video in the group

I was having the same problem. I don't know if your issue is the same as mine was, but I thought I'd share how I fixed mine. Do make sure the bot is allowed to see group messages, by default when creating a bot via @botfather on Telegram, they cannot see group messages. You need to disable privacy mode through the bot settings with @botfather. Then you'll need to remove the bot from the group and add it again. I hope that helps.

**Comment by ShamilSd-ux** [comment]
That is fine, but this doesn't satisfy my requirement. I don't want to send links in bot to send it to only one group. I want to add bot to different  groups that the bot should manage group. By posting links in group video should be reposted by bot, but that isn't happening

**Comment by ShamilSd-ux** [comment]
There should be additional coding to be done. I have accessed code using ChatGPT but don't know where to place it...
