### ISSUE TITLE
Error on Implementing Uploads to Channel

### ISSUE THREAD

**Issue by ShamilSd-ux** [tropicoo/yt-dlp-bot#185]
This is the error that is firing up when trying to implement uploads in telegram channel. Kindly resolve it...
yt_bot       | 2023-10-04 08:40:57,530 - [ERROR] - [pyrogram.dispatcher:253] - 'NoneType' object has no attribute 'id'
yt_bot       | Traceback (most recent call last):
yt_bot       |   File "/usr/local/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
yt_bot       |     await handler.callback(self.client, *args)
yt_bot       |   File "/app/bot/core/callbacks.py", line 42, in on_message
yt_bot       |     urls = self._url_parser.parse_urls(urls=urls, message=message, user=user)
yt_bot       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yt_bot       |   File "/app/bot/core/service.py", line 46, in parse_urls
yt_bot       |     return [
yt_bot       |            ^
yt_bot       |   File "/app/bot/core/service.py", line 51, in <listcomp>
yt_bot       |     from_user_id=message.from_user.id,
yt_bot       |                  ^^^^^^^^^^^^^^^^^^^^
yt_bot       | AttributeError: 'NoneType' object has no attribute 'id'

**Comment by tropicoo** [comment]
Fixed
