### ISSUE TITLE
Video has been uploaded two times on a single request

### ISSUE THREAD

**Issue by ShamilSd-ux** [tropicoo/yt-dlp-bot#186]
I've got an issue. Video is getting uploaded two times. I've commented out the group id at api part but it's still the same...

**Comment by tropicoo** [comment]
Check logs whether it’s uploaded two times or forwarded on the second time

**Comment by ShamilSd-ux** [comment]
I've resolved it just now . i have passed group id in the block also. there's the catch and i have removed it but i am confused of bool. Video is uploaded whether its true or false. Why?

**Comment by tropicoo** [comment]
I believe you have the same group ID in the forward section
