### ISSUE TITLE
How to rebuild?

### ISSUE THREAD

**Issue by sideloading** [tropicoo/yt-dlp-bot#227]
I am adjusting the config.yml but changes are not reflecting, even after re-attempting the run commands:

```
# Build base image
docker compose build base-image

# Build and run all services in detached mode
docker compose up --build -d -t 0 && docker compose logs --tail 100 -f

# Stop all services
docker compose stop -t 0
```

What am I missing to use the newest config.yml?

**Comment by tropicoo** [comment]
This command should rebuild with your changes `docker compose up --build -d -t 0`
