### ISSUE TITLE
Feature Request: Upload Audio 

### ISSUE THREAD

**Issue by J3rain** [tropicoo/yt-dlp-bot#51]
Hi,
i really like using your Bot! 
Could you add the Option to upload Audio to the Chat ?
I already tried it using the ytdl options, but it seems the bot doesn't want to send two files.
Thanks.

**Comment by tropicoo** [comment]
Hey, thanks for the kind words. How do you see the flow of this? You paste the video from youtube and want to receive back the video file (like currently) and additionally an audio file?

**Comment by tropicoo** [comment]
Released in 1.0
