### ISSUE TITLE
Video file not found

### ISSUE THREAD

**Issue by andersrh** [tropicoo/yt-dlp-bot#52]
When sending a Youtube URL to the bot it returns the following error:
🛑 General error

ℹ️ Task ID: 7e4854a8-399e-4c8c-9dac-6f00765f6e41
💬 Message: Upload error
📹 Video URL: https://www.youtube.com/watch?v=C0DPdy98e4c
🌊 Source: BOT
👀 Details: Traceback (most recent call last):
  File "/app/bot/core/handlers/success.py", line 28, in handle
    await self._handle()
  File "/app/bot/core/handlers/success.py", line 55, in _handle
    self._validate_file_size_for_upload(video_path)
  File "/app/bot/core/handlers/success.py", line 102, in _validate_file_size_for_upload
    raise ValueError(f'Video {video_path} not found')
ValueError: Video /tmp/download_tmpfs/TEST VIDEO.mp4 not found

⬇️ yt-dlp version: 2023.01.06
🏷️ Tag: #error

Errors from the log:

yt_worker    | 2023-02-05 21:30:30,961 - [INFO] - [VideoDownloader:33] - Downloading https://www.youtube.com/watch?v=C0DPdy98e4c
yt_worker    | 2023-02-05 21:30:30,962 - [INFO] - [VideoDownloader:37] - Downloading to /tmp/download_tmpfs/tmp_video_dir-j_s9nguy
yt_worker    | [youtube] Extracting URL: https://www.youtube.com/watch?v=C0DPdy98e4c
yt_worker    | [youtube] C0DPdy98e4c: Downloading webpage
yt_worker    | [youtube] C0DPdy98e4c: Downloading android player API JSON
yt_worker    | [info] C0DPdy98e4c: Downloading 1 format(s): 135+140
yt_worker    | [download] Destination: /tmp/download_tmpfs/tmp_video_dir-j_s9nguy/TEST VIDEO.f135.mp4
[download] 100% of  155.85KiB in 00:00:00 at 1.31MiB/s
yt_worker    | [download] Destination: /tmp/download_tmpfs/tmp_video_dir-j_s9nguy/TEST VIDEO.f140.m4a
[download] 100% of  279.31KiB in 00:00:00 at 4.05MiB/s
yt_worker    | [Merger] Merging formats into "/tmp/download_tmpfs/tmp_video_dir-j_s9nguy/TEST VIDEO.mp4"
yt_worker    | Deleting original file /tmp/download_tmpfs/tmp_video_dir-j_s9nguy/TEST VIDEO.f140.m4a (pass -k to keep)
yt_worker    | Deleting original file /tmp/download_tmpfs/tmp_video_dir-j_s9nguy/TEST VIDEO.f135.mp4 (pass -k to keep)
yt_worker    | 2023-02-05 21:30:32,458 - [INFO] - [VideoDownloader:47] - Finished downloading https://www.youtube.com/watch?v=C0DPdy98e4c
yt_worker    | 2023-02-05 21:30:32,458 - [INFO] - [VideoDownloader:52] - Moving /tmp/download_tmpfs/tmp_video_dir-j_s9nguy/TEST VIDEO.mp4 to /tmp/download_tmpfs
yt_worker    | 2023-02-05 21:30:32,458 - [INFO] - [VideoDownloader:53] - Content of /tmp/download_tmpfs/tmp_video_dir-j_s9nguy: ['TEST VIDEO.mp4']
yt_worker    | 2023-02-05 21:30:32,458 - [INFO] - [VideoDownloader:55] - Removing /tmp/download_tmpfs/tmp_video_dir-j_s9nguy
yt_worker    | 2023-02-05 21:30:32,467 - [INFO] - [asyncio:1658] - run shell command 'ffmpeg -y -loglevel error -i "/tmp/download_tmpfs/TEST VIDEO.mp4" -ss 10.0 -vframes 1 -q:v 7 "/tmp/download_tmpfs/TEST VIDEO.mp4-thumb.jpg"': <_UnixSubprocessTransport pid=45 running stdout=<_UnixReadPipeTransport fd=8 polling> stderr=<_UnixReadPipeTransport fd=10 polling>>
yt_worker    | 2023-02-05 21:30:32,962 - [INFO] - [asyncio:525] - <_UnixReadPipeTransport fd=10 polling> was closed by peer
yt_worker    | 2023-02-05 21:30:32,962 - [INFO] - [asyncio:525] - <_UnixReadPipeTransport fd=8 polling> was closed by peer
yt_worker    | 2023-02-05 21:30:32,963 - [INFO] - [asyncio:211] - <_UnixSubprocessTransport pid=45 running stdout=<_UnixReadPipeTransport closed fd=8 closed> stderr=<_UnixReadPipeTransport closed fd=10 closed>> exited with return code 0
yt_worker    | 2023-02-05 21:30:32,977 - [INFO] - [sqlalchemy.engine.Engine:2666] - BEGIN (implicit)
yt_worker    | 2023-02-05 21:30:32,982 - [INFO] - [sqlalchemy.engine.Engine:1842] - SELECT file.id AS file_id, file.title AS file_title, file.name AS file_name, file.thumb_name AS file_thumb_name, file.duration AS file_duration, file.width AS file_width, file.height AS file_height, file.meta AS file_meta, file.task_id AS file_task_id, file.created AS file_created, file.updated AS file_updated
yt_worker    | FROM file
yt_worker    | WHERE $1::UUID = file.task_id
yt_worker    | 2023-02-05 21:30:32,982 - [INFO] - [sqlalchemy.engine.Engine:1842] - [generated in 0.00035s] ('7e4854a8-399e-4c8c-9dac-6f00765f6e41',)
yt_worker    | 2023-02-05 21:30:32,988 - [INFO] - [sqlalchemy.engine.Engine:1842] - UPDATE task SET status=$1::taskstatus, updated=$2::TIMESTAMP WITHOUT TIME ZONE WHERE task.id = $3::UUID
yt_worker    | 2023-02-05 21:30:32,988 - [INFO] - [sqlalchemy.engine.Engine:1842] - [cached since 2.035s ago] ('DONE', datetime.datetime(2023, 2, 5, 21, 30, 32, 987898), '7e4854a8-399e-4c8c-9dac-6f00765f6e41')
yt_worker    | 2023-02-05 21:30:32,994 - [INFO] - [sqlalchemy.engine.Engine:1842] - INSERT INTO file (id, title, name, thumb_name, duration, width, height, meta, task_id, created, updated) VALUES ($1::UUID, $2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::INTEGER, $6::INTEGER, $7::INTEGER, $8::JSONB, $9::UUID, $10::TIMESTAMP WITHOUT TIME ZONE, $11::TIMESTAMP WITHOUT TIME ZONE)
yt_worker    | 2023-02-05 21:30:32,994 - [INFO] - [sqlalchemy.engine.Engine:1842] - [generated in 0.00243s] ('ddd8a7cc-4ee5-49e9-955b-6c96e7dfc5a8', 'TEST VIDEO', 'TEST VIDEO.mp4', 'TEST VIDEO.mp4-thumb.jpg', 18.0, 640, 480, '{"id": "C0DPdy98e4c", "title": "TEST VIDEO", "formats": [{"format_id": "sb2", "format_note": "storyboard", "ext": "mhtml", "protocol": "mhtml", "acod ... (52442 characters truncated) ... 632, "_type": "video", "_version": {"version": "2023.01.06", "current_git_head": null, "release_git_head": "6becd25", "repository": "yt-dlp/yt-dlp"}}', '7e4854a8-399e-4c8c-9dac-6f00765f6e41', datetime.datetime(2023, 2, 5, 21, 30, 32, 992086), datetime.datetime(2023, 2, 5, 21, 30, 32, 992095))
yt_worker    | 2023-02-05 21:30:33,003 - [INFO] - [sqlalchemy.engine.Engine:2672] - COMMIT
yt_worker    | 2023-02-05 21:30:33,015 - [INFO] - [_RMQCallbacks:32] - Processing done with payload: id=None from_chat_id=***** from_chat_type=<TelegramChatType.PRIVATE: 'private'> from_user_id=***** message_id=25 url='https://www.youtube.com/watch?v=C0DPdy98e4c' source=<TaskSource.BOT: 'BOT'> added_at=datetime.datetime(2023, 2, 5, 21, 30, 28, 139, tzinfo=datetime.timezone.utc)
yt_bot       | 2023-02-05 21:30:33,016 - [INFO] - [SuccessResultWorker:53] - [x] Received message b'{"type":3,"task_id":"7e4854a8-399e-4c8c-9dac-6f00765f6e41","from_chat_id":*****,"from_chat_type":"private","from_user_id":*****,"message_id":25,"title":"TEST VIDEO","filename":"TEST VIDEO.mp4","thumb_name":"TEST VIDEO.mp4-thumb.jpg","duration":18.0,"width":640,"height":480,"context":{"id":null,"from_chat_id":*****,"from_chat_type":"private","from_user_id":*****,"message_id":25,"url":"https://www.youtube.com/watch?v=C0DPdy98e4c","source":"BOT","added_at":"2023-02-05T21:30:28.000139+00:00"},"yt_dlp_version":"2023.01.06"}'
yt_bot       | 2023-02-05 21:30:33,130 - [ERROR] - [SuccessHandler:58] - Upload of "/tmp/download_tmpfs/TEST VIDEO.mp4" failed, performing cleanup
yt_bot       | 2023-02-05 21:30:33,139 - [INFO] - [ErrorResultWorker:53] - [x] Received message b'{"type":2,"task_id":"7e4854a8-399e-4c8c-9dac-6f00765f6e41","from_chat_id":*****,"from_chat_type":"private","from_user_id":*****,"message_id":25,"message":"Upload error","url":"https://www.youtube.com/watch?v=C0DPdy98e4c","context":{"id":null,"from_chat_id":*****,"from_chat_type":"private","from_user_id":*****,"message_id":25,"url":"https://www.youtube.com/watch?v=C0DPdy98e4c","source":"BOT","added_at":"2023-02-05T21:30:28.000139+00:00"},"exception_msg":"Traceback (most recent call last):\\n  File \\"/app/bot/core/handlers/success.py\\", line 28, in handle\\n    await self._handle()\\n  File \\"/app/bot/core/handlers/success.py\\", line 55, in _handle\\n    self._validate_file_size_for_upload(video_path)\\n  File \\"/app/bot/core/handlers/success.py\\", line 102, in _validate_file_size_for_upload\\n    raise ValueError(f\'Video {video_path} not found\')\\nValueError: Video /tmp/download_tmpfs/TEST VIDEO.mp4 not found\\n","exception_type":"ValueError","yt_dlp_version":"2023.01.06"}'

**Comment by tropicoo** [comment]
I've just released a new version 0.7. It should fix this bug. Please update your bot.

**Comment by andersrh** [comment]
I have tested with the newest version and it works now.

**Comment by andersrh** [comment]
Sorry for asking this in the wrong place, but I don't know where else to ask.
Does the bot support video download in groups? So I can invite the bot to a group and whenever a link is sent in the group, then the bot will post the video there.

**Comment by tropicoo** [comment]
@andersrh Yes, you can do this. You just need to add a new user in the `config.yml` under `allowed_users` key. By default there is a one user, just copy/paste your user and replace id with id of your group.

**Comment by andersrh** [comment]
> @andersrh Yes, you can do this. You just need to add a new user in the `config.yml` under `allowed_users` key. By default there is a one user, just copy/paste your user section and replace id of your user with id of your group.

It works. Thank you. Is it possible to allow anyone to use the bot and have exception list to that? If not then I might wanna make a pull request with some changes. I hope that would be welcomed in that case :-)

**Comment by tropicoo** [comment]
> If not then I might wanna make a pull request with some changes. I hope that would be welcomed in that case :-)
Sure, go ahead
