### ISSUE TITLE
Work From within a group?

### ISSUE THREAD

**Issue by physk** [tropicoo/yt-dlp-bot#91]
Is there any way to get it to work from within a group?

For example I could setup a group with some friends and they can just post a link in the group and it downloads it for them rather than having to set each friend up manually?

**Comment by tropicoo** [comment]
Yes, you just need to put your group/chat ID into the config:

```yaml
allowed_users:
    - id: -123456789
```

**Comment by physk** [comment]
I tried that, The Bot never reads it or responds. (I even gave it admin on the channel so it had full access)

**Comment by tropicoo** [comment]
I see, I will look into that

**Comment by physk** [comment]
Thank you! I am here if you would like any more information!

**Comment by tropicoo** [comment]
I've just updated bot to the version 1.3. It should work now as I've written before. 
Please test.

**Comment by physk** [comment]
Worked out why! I had my account set to Anonymous!

![image](https://user-images.githubusercontent.com/32438947/228101722-b40e80db-d223-4fb5-a3ee-7efc0ab14c8c.png)
This needs to be turned off.

Working now... thank you!

**Comment by tropicoo** [comment]
> One thing you might want to do is put a filter for only URL's in groups though or maybe have to have a prefix as it responds to all messages (erroring)

Added that in a new release 1.4: Details in https://github.com/tropicoo/yt-dlp-bot/blob/main/RELEASES.md

**Comment by physk** [comment]
Excellent. Seems to be working. Thank you! 🙏

**Comment by tropicoo** [comment]
Cool!
