### ISSUE TITLE
API_HOST and API_PORT Error

### ISSUE THREAD

**Issue by kzhiga** [tropicoo/yt-dlp-bot#96]
Доброго Дня. Зіткнувся з такою помилкою:

yt_bot       | Waiting for RabbitMQ to be reachable on port 5672
yt_bot       | Waiting for PostgreSQL to be reachable on port 5432
yt_bot       | Connection to RabbitMQ on port 5672 verified
yt_bot       | Connection to PostgreSQL on port 5432 verified
yt_bot       | Traceback (most recent call last):
yt_bot       |   File "/app/main.py", line 3, in <module>
yt_bot       |     from api.core.app import app  # noqa: F401
yt_bot       |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yt_bot       |   File "/app/api/core/app.py", line 10, in <module>
yt_bot       |     from api.core.config import settings
yt_bot       |   File "/app/api/core/config.py", line 9, in <module>
yt_bot       |     settings = ApiSettings()
yt_bot       |                ^^^^^^^^^^^^^
yt_bot       |   File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
yt_bot       |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
yt_bot       | pydantic.error_wrappers.ValidationError: 2 validation errors for ApiSettings
yt_bot       | API_HOST
yt_bot       |   field required (type=value_error.missing)
yt_bot       | API_PORT
yt_bot       |   field required (type=value_error.missing)

Інші контейнери працюють добре. Пробував через API скачати відео, все супер)
А сам бот не працює. Мабуть, це пов'язано з цією помилкою. Чи можу я це якось виправити? Дякую

**Comment by tropicoo** [comment]
Доброго дня,

Помилка доволі дивна, так як:
1. Належить контейнеру `yt_api`, хоча у вас показує `yt_bot`
2. В теорії ви не могли б завантажити через API, бо цей контейнер не мав би запуститись і нормально функціонувати, так як АРІ-сервер вимагає хост та порт для запуску, а у вас вибило помилку (хоча її не повинно бути, так як параметри підтягуються з `envs/.env_api`)

Спробуйте видалити контейнери та імеджі і ще раз все перезібрати.

**Comment by kzhiga** [comment]
Дуже Вам вдячний за відповідь=)
Дякую, шо направили. Знайшов в envs/.env_api, строку
API_HOST=0.0.0.0
Змінив на 
API_HOST=192.168.10.162
IP на якому стоїть docker.
Все запрацювало. Вдячний
Слава Україні!

**Comment by tropicoo** [comment]
Звертайтесь :)
Героям Слава!
